# ===========================
# BACKTEST CONFIGURATION - OPTIMIZADO
# ===========================

# Trading Pair
symbol1: "MEXCFTS_PERP_WIF_USDT"
symbol2: "MEXCFTS_PERP_POPCAT_USDT"

# Backtest Period
start_date: 2024-12-01
end_date: 2025-08-01

# ===========================
# CAPITAL & RISK MANAGEMENT
# ===========================
initial_capital: 10000
position_size: 0.1
max_positions: 1

# ===========================
# EXECUTION CONFIGURATION - CORREGIDO
# ===========================
execution:
  commission_bps: 2.0
  use_orderbook: false
  fallback_slippage_bps: 5.0  # CORREGIDO: era 1e-07
  max_participation_rate: 0.10
  orderbook_time_tolerance_seconds: 450

# ===========================
# DATA CONFIGURATION
# ===========================
data:
  resample_minutes: 15

# ===========================
# PAIRS STRATEGY PARAMETERS - OPTIMIZADO
# ===========================
strategy:
  # Ventanas EN DÍAS
  lookback_window: 7           # días para z-score
  hedge_ratio_window: 60       # días para hedge ratio
  rebalance_frequency: "never"

  # THRESHOLDS OPTIMIZADOS
  entry_threshold: 2.0         # Más conservador
  exit_threshold: 0.0          # CORREGIDO: salir en la media
  stop_loss_threshold: 4.0

  min_correlation: 0.5
  use_robust_zscore: false     # Usar std tradicional

  signal_confirmation_bars: 0
  max_holding_periods: 0

# ===========================
# LOGGING & OUTPUT
# ===========================
output:
  save_trades: true
  save_signals: true
  save_equity_curve: true
  generate_plots: true
  verbose: true