# ===========================
# BACKTEST CONFIGURATION - FINAL OPTIMIZED
# ===========================

# Trading Pair
symbol1: "MEXCFTS_PERP_WIF_USDT"
symbol2: "MEXCFTS_PERP_POPCAT_USDT"

# Backtest Period
start_date: 2024-12-01
end_date: 2025-08-01

# ===========================
# CAPITAL & RISK MANAGEMENT
# ===========================
initial_capital: 10000
position_size: 0.3
max_positions: 1

# ===========================
# EXECUTION CONFIGURATION
# ===========================
execution:
  commission_bps: 0
  use_orderbook: false
  fallback_slippage_bps: 0
  max_participation_rate: 0.10
  orderbook_time_tolerance_seconds: 450

# ===========================
# DATA CONFIGURATION
# ===========================
data:
  resample_minutes: 15

# ===========================
# PAIRS STRATEGY PARAMETERS - FINAL TUNING
# ===========================
strategy:
  # Ventanas temporales (en DÍAS)
  lookback_window: 10
  hedge_ratio_window: 20
  rebalance_frequency: "never"

  # Trading thresholds - AJUSTADOS
  entry_threshold: 2
  exit_threshold: 0           
  stop_loss_threshold: 4

  # Correlación
  min_correlation: 0.7
  min_correlation_rolling: 0.6
  
  # Hedge Ratio Quality - RELAJADO
  min_r_squared: 0.7
  max_hedge_ratio: 3
  min_hedge_ratio: 0.3
  
  # Risk Management - AJUSTADO
  max_position_hours: 48
  
  # Volatility adjustment
  volatility_lookback_hours: 24
  high_volatility_multiplier: 1.5
  position_size_reduction: 0.5
  
  # Otros
  use_robust_zscore: false
  signal_confirmation_bars: 0
  max_holding_periods: 0

# ===========================
# LOGGING & OUTPUT
# ===========================
output:
  save_trades: true
  save_signals: true
  save_equity_curve: true
  generate_plots: true
  verbose: true