# ===========================
# BACKTEST CONFIGURATION
# ===========================

# Trading Pair
symbol1: "MEXCFTS_PERP_WIF_USDT"
symbol2: "MEXCFTS_PERP_POPCAT_USDT"

# Backtest Period
start_date: 2024-12-01
end_date: 2025-08-09

# ===========================
# CAPITAL & RISK MANAGEMENT
# ===========================
initial_capital: 10000
position_size: 0.05  # 5% of capital per trade (conservative for testing)
max_positions: 1     # Maximum simultaneous positions

# ===========================
# EXECUTION CONFIGURATION
# ===========================
execution:
  commission_bps: 2.0           # 0.02% - Exchange taker fee
  use_orderbook: false           # Use real orderbook for dynamic slippage
  fallback_slippage_bps: 10.0    # 0.05% - Used when orderbook data unavailable
  max_participation_rate: 0.1   # Max 10% of volume per trade

# ===========================
# DATA CONFIGURATION
# ===========================
data:
  resample_minutes: 15  # 15-minute bars for smoother signals

# ===========================
# PAIRS STRATEGY PARAMETERS
# ===========================
strategy:
  # Window Configuration (7 days, no rebalancing)
  lookback_window: 7            # 7-day window for z-score calculation
  hedge_ratio_window: 7         # Use same 7-day window for hedge ratio
  rebalance_frequency: 999999   # Effectively never rebalance (set very high)
  
  # Entry/Exit Thresholds
  entry_threshold: 1.75         # Enter when |z-score| > 1.75
  exit_threshold: 0.25          # Exit when z-score crosses 0.25
  stop_loss_threshold: 4.0      # Stop loss at |z-score| > 4.0
  
  # Quality Filters
  min_correlation: 0.5          # Minimum correlation required
  use_robust_zscore: true       # Use MAD-based robust z-score
  
  # Additional Parameters (optional)
  signal_confirmation_bars: 0   # No confirmation needed (0 = immediate execution)
  max_holding_periods: 0        # No maximum holding period (0 = unlimited)

# ===========================
# LOGGING & OUTPUT
# ===========================
output:
  save_trades: true
  save_signals: true
  save_equity_curve: true
  generate_plots: true
  verbose: true

# ===========================
# NOTES
# ===========================
# This configuration uses:
# - 7-day lookback window with NO rebalancing (fixed hedge ratio)
# - Conservative 5% position sizing for testing
# - Real orderbook data for accurate slippage calculation
# - Entry at |z| > 1.75 (slightly relaxed for more signals)
# - Exit at z crosses 0.25 (partial mean reversion)
# - Stop loss at |z| > 4.0 (extreme moves)