# ===========================
# BACKTEST CONFIGURATION
# ===========================

# Trading Pair
symbol1: "MEXCFTS_PERP_WIF_USDT"
symbol2: "MEXCFTS_PERP_POPCAT_USDT"

# Backtest Period
start_date: 2024-12-01
end_date: 2025-08-01

# ===========================
# CAPITAL & RISK MANAGEMENT
# ===========================
initial_capital: 10000
position_size: 0.1
max_positions: 1

# ===========================
# EXECUTION CONFIGURATION
# ===========================
execution:
  commission_bps: 2.0
  use_orderbook: false
  fallback_slippage_bps: 0.01
  max_participation_rate: 0.10
  # Tolerancia temporal para casar vela con orderbook (en segundos):
  # si lo omites, se usa la mitad de resample_minutes.
  orderbook_time_tolerance_seconds: 450   # 7.5 min (para velas de 15m)

# ===========================
# DATA CONFIGURATION
# ===========================
data:
  resample_minutes: 15

# ===========================
# PAIRS STRATEGY PARAMETERS
# ===========================
strategy:
  # Ventanas EN DÍAS (no barras)
  lookback_window: 7
  hedge_ratio_window: 7
  rebalance_frequency: "never"   # muy alto = no rebalancea

  entry_threshold: 2
  exit_threshold: 0.5
  stop_loss_threshold: 4.0

  min_correlation: 0.5
  use_robust_zscore: true

  signal_confirmation_bars: 0
  max_holding_periods: 0

# ===========================
# LOGGING & OUTPUT
# ===========================
output:
  save_trades: true
  save_signals: true
  save_equity_curve: true
  generate_plots: true
  verbose: true